version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: truongnv
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log/:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
  links:
      - mysql
      
  mysql:
    image: mysql:latest
    container_name: mysql_truong
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
